module.exports = {
  themes: [
    {
      template: "NWT",
      name: "NWT",
      input: "index",
      output: "style-nwt"
    }, {
      template: "VF",
      name: "VF",
      input: "index",
      output: "style-vf"
    }, {
      template: "arvika-nyheter",
      name: "AN",
      input: "index",
      output: "style-arvika-nyheter"
    }, {
      template: "dalslanningen",
      name: "DAL",
      input: "index",
      output: "style-dalslanningen"
    }, {
      template: "frykdals-bygden",
      name: "FB",
      input: "index",
      output: "style-frykdals-bygden"
    }, {
      template: "filipstads-tidning",
      name: "FT",
      input: "index",
      output: "style-filipstads-tidning"
    }, {
      template: "karlskoga-tidning",
      name: "KT",
      input: "index",
      output: "style-karlskoga-tidning"
    }, {
      template: "karlskoga-kuriren",
      name: "KK",
      input: "index",
      output: "style-karlskoga-kuriren"
    }, {
      template: "kristinehamns-posten",
      name: "KNP",
      input: "index",
      output: "style-kristinehamns-posten"
    }, {
      template: "provinstidningen",
      name: "PD",
      input: "index",
      output: "style-provinstidningen"
    }, {
      template: "saffle-tidningen",
      name: "ST",
      input: "index",
      output: "style-saffle-tidningen"
    }, {
      template: "skaraborgs-allehanda",
      name: "SLA",
      input: "index",
      output: "style-skaraborgs-allehanda"
    }, {
      template: "hjo-tidning",
      name: "HT",
      input: "index",
      output: "style-hjo-tidning"
    }, {
      template: "mariestads-tidningen",
      name: "MT",
      input: "index",
      output: "style-mariestads-tidningen"
    }, {
      template: "VF", // Default theme for docs
      name: "docs",
      input: "dev-index",
      output: "style"
    }, {
      template: "NWT",
      name: "matchads-nwt",
      input: "matchads-index",
      output: "style-matchads-nwt"
    }, {
      template: "VF",
      name: "matchads-vf",
      input: "matchads-index",
      output: "style-matchads-vf"
    }, {
      template: "arvika-nyheter",
      name: "matchads-an",
      input: "matchads-index",
      output: "style-matchads-an"
    }, {
      template: "dalslanningen",
      name: "matchads-dal",
      input: "matchads-index",
      output: "style-matchads-dal"
    }, {
      template: "frykdals-bygden",
      name: "matchads-fb",
      input: "matchads-index",
      output: "style-matchads-fb"
    }, {
      template: "filipstads-tidning",
      name: "matchads-ft",
      input: "matchads-index",
      output: "style-matchads-ft"
    }, {
      template: "karlskoga-tidning",
      name: "matchads-kt",
      input: "matchads-index",
      output: "style-matchads-kt"
    }, {
      template: "karlskoga-kuriren",
      name: "matchads-kk",
      input: "matchads-index",
      output: "style-matchads-kk"
    }, {
      template: "kristinehamns-posten",
      name: "matchads-knp",
      input: "matchads-index",
      output: "style-matchads-knp"
    }, {
      template: "provinstidningen",
      name: "matchads-pd",
      input: "matchads-index",
      output: "style-matchads-pd"
    }, {
      template: "saffle-tidningen",
      name: "matchads-st",
      input: "matchads-index",
      output: "style-matchads-st"
    }, {
      template: "skaraborgs-allehanda",
      name: "matchads-sla",
      input: "matchads-index",
      output: "style-matchads-sla"
    }, {
      template: "hjo-tidning",
      name: "matchads-ht",
      input: "matchads-index",
      output: "style-matchads-ht"
    }, {
      template: "mariestads-tidningen",
      name: "matchads-mt",
      input: "matchads-index",
      output: "style-matchads-mt",
    },
  ]
};
