FROM node:10.6.0

RUN mkdir -p /usr/src/app/src/
WORKDIR /usr/src/app

COPY src/. /usr/src/app/src/
COPY bundling/. /usr/src/app/bundling/

COPY package.json /usr/src/app/
RUN npm install
RUN npm run build

CMD [ "npm", "run", "server:dev" ]
