#!/bin/bash

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_REGION
unset KOPS_CLUSTER
unset CLUSTER
unset KOPS_STATE_STORE

export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export AWS_REGION=us-east-1

export CLUSTER=
export KOPS_STATE_STORE=
