# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 2.2.0"
VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('servers.yaml')

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Iterate through entries in YAML file
  servers.each do |servers|
    config.vm.define servers["name"] do |srv|
      srv.vm.synced_folder './src/', '/vagrant', disabled: false
      srv.vm.hostname = servers["name"]
      srv.vm.box = servers["box"]
      srv.disksize.size = servers["disksize"]
      srv.vm.network "private_network", ip: servers["ip"]
      srv.vm.network :forwarded_port, guest: 22, host: servers["port"], host_ip: "localhost", id: 'ssh'
      srv.vm.provision "shell", path: servers["provision_script"]
      srv.vm.provider :vmware_desktop do |v|
        v.vmx['displayName'] = servers["name"]
        v.vmx['memsize'] = servers["ram"]
        v.vmx['numvcpus'] = servers["cpu"]
      end
    end
  end
end
